name: Build and Push Sensor Docker Image

on:
  push:
    paths:
      - 'sensor/**'
      - '.github/workflows/build-sensor.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Docker image
        run: docker build -t teu-user/simulador-sensor:latest ./sensor
      - name: Push Docker image
        run: docker push teu-user/simulador-sensor:latest
